spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/techstack_insight}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  ingestion:
    run-on-startup: false
    scheduler-enabled: false
    scheduler-cron: "0 0 3 * * *"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

